package com.tch.test.springboot.mapper;

import com.tch.test.springboot.model.StudentPO;
import java.util.List;

public interface StudentPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri May 19 15:32:28 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri May 19 15:32:28 CST 2017
     */
    int insert(StudentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri May 19 15:32:28 CST 2017
     */
    StudentPO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri May 19 15:32:28 CST 2017
     */
    List<StudentPO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri May 19 15:32:28 CST 2017
     */
    int updateByPrimaryKey(StudentPO record);
}